global:
  domain: consul
  datacenter: dc2
  imageK8S: ndhanushkodi/consul-k8s-dev:peering36
  image: ndhanushkodi/consul-dev:peering10
  # image: ndhanushkodi/consul-dev:entpeering4
  # enterpriseLicense:
  #   secretName: license
  #   secretKey: key
  peering:
    enabled: true
server:
  replicas: 1
  bootstrapExpect: 1
  extraConfig: |
    {
      "log_level": "TRACE"
    }

client:
  enabled: true
  grpc: true
  extraConfig: |
    {
      "log_level": "TRACE"
    }

ui:
  enabled: true

connectInject:
  enabled: true

controller:
  enabled: true

meshGateway:
  enabled: true
  replicas: 1
